# Generated by Django 4.2.11 on 2024-03-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='email',
            field=models.EmailField(default='SOME STRING', max_length=250),
        ),
        migrations.AddField(
            model_name='userdata',
            name='password1',
            field=models.CharField(default='SOME STRING', max_length=250),
        ),
        migrations.AddField(
            model_name='userdata',
            name='password2',
            field=models.CharField(default='SOME STRING', max_length=250),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='dp',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
