# Generated by Django 4.2.11 on 2024-03-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_userdata_dp'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='SOME STRING', max_length=250)),
                ('release', models.DateTimeField()),
                ('description', models.TextField()),
                ('movie_length', models.IntegerField()),
                ('cover', models.ImageField(upload_to='gallery')),
                ('genre', models.CharField(default='SOME STRING', max_length=250)),
            ],
        ),
    ]
