# Generated by Django 4.2.11 on 2024-03-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_addmovie'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmovie',
            name='url',
            field=models.CharField(default='SOME STRING', max_length=250),
        ),
    ]
