# Generated by Django 4.2.11 on 2024-03-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_addmovie_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmovie',
            name='actor',
            field=models.CharField(default='SOME STRING', max_length=250),
        ),
    ]
