# Generated by Django 4.2.11 on 2024-03-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_addmovie_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmovie',
            name='actor',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
