# Generated by Django 4.2.11 on 2024-03-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmovie',
            name='rating',
            field=models.CharField(default='SOME STRING', max_length=250),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
