# Generated by Django 4.2.11 on 2024-03-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_addmovie_comment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
