# Generated by Django 4.2.11 on 2024-03-09 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
